# Generated by Django 4.1.5 on 2023-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Payer à la livraison'), ('pi_network', 'Payer par Pi Network')], default='cash_on_delivery', max_length=20),
        ),
    ]
