# Generated by Django 4.1.5 on 2023-01-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=150)),
                ('qte', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('adresse', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to='media', verbose_name='photo de profile')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=150)),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='image')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=150)),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='image')),
                ('shop', models.ManyToManyField(to='shop.shop')),
            ],
        ),
    ]
