# Generated by Django 4.1.5 on 2023-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='shop', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='shop', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.ImageField(upload_to='shop', verbose_name='photo de profile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shop', verbose_name='image'),
        ),
    ]
