# Generated by Django 4.1.5 on 2023-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_article_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='market',
            name='adresse',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
