# Generated by Django 4.1.5 on 2023-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_article_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=None, upload_to='shop', verbose_name='image'),
        ),
    ]
