# Generated by Django 4.1.5 on 2023-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fonction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Vendor'), (3, 'Customer'), (4, 'Deliveryman')], default=3, null=True),
        ),
    ]
