# Generated by Django 4.1.5 on 2023-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=22797557852, max_length=15, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
