# Generated by Django 4.1.5 on 2023-01-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='user/static/user/images', verbose_name='photo de profile'),
        ),
    ]
