# Generated by Django 4.1.5 on 2023-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fonction',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Vendor'), (3, 'Customer'), (4, 'Deliveryman')], default=3, null=True),
        ),
    ]
