# Generated by Django 4.1.5 on 2023-04-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publicites', verbose_name='image')),
                ('description', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('duree_diffusion', models.IntegerField(default=7)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
